apiVersion: v1
kind: Pod
metadata:
  name: mongodb-client
  labels:
    app: mongo
spec:
  containers:
    - name: mongodb-client
      image: mongo:4
      command:
        - bash
        - -c
        - sleep infinity
