apiVersion: v1
kind: Pod
metadata:
  name: gateway
  labels:
    app: gw
spec:
  containers:
    - name: shell-in-pod
      image: bitbox/k8s-training-tools:v1
      command:
        - bash
        - -c
        - sleep infinity
