---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: multi-ports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-ports
  template:
    metadata:
      labels:
        app: multi-ports
    spec:
      containers:
        - name: multi-ports-app
          image: alpine:3.12
          command:
            - ash
            - -c
            - (while true; do echo "web $(date)" | nc -l -p 80; done & while true; do echo "admin $(date -Iseconds)" | nc -l -p 1234; done)
          ports:
            - name: web-port
              containerPort: 80
            - name: admin-port
              containerPort: 1234
