---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami
      level: expert
  replicas: 2
  template:
    metadata:
      labels:
        app: whoami
        level: expert
    spec:
      containers:
        - name: whoami
          image: containous/whoami:latest
          ports:
            - name: main-port
              containerPort: 80
