apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: debian:10-slim
              args:
                - bash
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
