---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-and-clock
spec:
  terminationGracePeriodSeconds: 2
  containers:
    - name: whoami
      image: containous/whoami:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
    - name: clock
      image: debian:10-slim
      command:
        - bash
        - -c
        - while true; do date | tee /dev/stderr; sleep 1; done
