---
apiVersion: v1
kind: Pod
metadata:
  name: civil-war
spec:
  containers:
    - name: revelation
      image: debian:10-slim
      command: [ "bash", "-c", "env ; sleep infinity" ]
      env:
        - name: SPIDERMAN_IS
          valueFrom:
            secretKeyRef:
              name: secret-identities
              key: spiderman
